#!/bin/bash
# Quick reference for running the QBotix Rover system

echo "=========================================="
echo "QBotix Rover Quick Reference"
echo "=========================================="
echo ""
echo "Run these commands in SEPARATE terminal windows:"
echo ""
echo "# Terminal 1 - ZED Camera"
echo "cd ~/ros2_ws && source install/setup.bash"
echo "ros2 launch qbotix_rover zed_camera.launch.py"
echo ""
echo "# Terminal 2 - Robot Model & TF"
echo "cd ~/ros2_ws && source install/setup.bash"
echo "ros2 launch qbotix_rover rover_bringup.launch.py"
echo ""
echo "# Terminal 3 - Navigation Stack"
echo "cd ~/ros2_ws && source install/setup.bash"
echo "ros2 launch qbotix_navigation navigation.launch.py"
echo ""
echo "# Terminal 4 - Cone Detection"
echo "cd ~/ros2_ws && source install/setup.bash"
echo "ros2 launch qbotix_perception perception.launch.py"
echo ""
echo "# Terminal 5 - RViz (Optional)"
echo "cd ~/ros2_ws && source install/setup.bash"
echo "rviz2"
echo ""
echo "=========================================="
echo "Monitoring Commands (run in new terminals)"
echo "=========================================="
echo ""
echo "# Monitor detected cone poses"
echo "ros2 topic echo /cone_pose"
echo ""
echo "# Monitor navigation goals"
echo "ros2 topic echo /goal_pose"
echo ""
echo "# Monitor robot velocity commands"
echo "ros2 topic echo /cmd_vel"
echo ""
echo "# Check active nodes"
echo "ros2 node list"
echo ""
echo "# Check available topics"
echo "ros2 topic list"
echo ""
echo "# View TF tree"
echo "ros2 run tf2_tools view_frames && evince frames.pdf"
echo ""
echo "=========================================="
echo "Manual Testing"
echo "=========================================="
echo ""
echo "# Send manual navigation goal (2m forward)"
echo "ros2 topic pub --once /goal_pose geometry_msgs/PoseStamped \\"
echo "'{header: {frame_id: \"map\"}, pose: {position: {x: 2.0, y: 0.0, z: 0.0}, orientation: {w: 1.0}}}'"
echo ""
echo "# Disable auto-navigation"
echo "ros2 param set /target_publisher auto_navigate false"
echo ""
echo "# Enable auto-navigation"
echo "ros2 param set /target_publisher auto_navigate true"
echo ""
echo "# Check cone detector parameters"
echo "ros2 param list /cone_detector"
echo ""
echo "=========================================="
